
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mumzhnntceqgqdkrnhbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11bXpobm50Y2VxZ3Fka3JuaGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTgwNjksImV4cCI6MjA2MjgzNDA2OX0.7WFq5mxtbr78ZC1D3tfepAKNVgymQvSFXCn9jQR-PXg";

// Custom cookie storage for better session persistence
const cookieStorage = {
  getItem: (key: string) => {
    if (typeof document === 'undefined') return null;
    const value = document.cookie
      .split('; ')
      .find(row => row.startsWith(`${key}=`))
      ?.split('=')[1];
    return value ? decodeURIComponent(value) : null;
  },
  setItem: (key: string, value: string) => {
    if (typeof document === 'undefined') return;
    const maxAge = 60 * 60 * 24 * 30; // 30 days
    document.cookie = `${key}=${encodeURIComponent(value)}; max-age=${maxAge}; path=/; SameSite=Lax; Secure=${location.protocol === 'https:'}`;
  },
  removeItem: (key: string) => {
    if (typeof document === 'undefined') return;
    document.cookie = `${key}=; expires=Thu, 01 Jan 1970 00:00:00 UTC; path=/;`;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: cookieStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
